apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: product-service
          image: ghcr.io/bisiswostik04-design/shopsphere-product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002

          env:
            - name: PORT
              value: "5002"

            - name: MONGO_URL
              value: "mongodb://$(MONGO_HOST):$(MONGO_PORT)/$(MONGO_DATABASE)_products"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopsphere-secret
                  key: JWT_SECRET

          envFrom:
            - configMapRef:
                name: shopsphere-config

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopsphere
spec:
  selector:
    app: product-service
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP
